@startuml
skinparam classAttributeIconSize 0
hide circle

abstract class Client {
  идентификатор_клиента
  ИНН
  контактные_данные
  статус_проверки : "пройдена/не пройдена"
  дата_верификации
  источник_верификации : "ЕСИА/банк"
}

class PhysicalClient {
  ФИО
  паспортные_данные
  адрес_регистрации
}

class LegalClient {
  наименование
  ОГРН
  юридический_адрес
  список_бенефициаров
}

Client <|-- PhysicalClient
Client <|-- LegalClient

class DigitalWallet {
  идентификатор_кошелька
  остаток_средств
  статус : "активен/заблокирован"
  тип_кошелька : "онлайн/офлайн"
  дата_последней_синхронизации
  хэш_последней_операции
}

class OfflineOperation {
  идентификатор_операции
  тип_операции : "платеж/перевод"
  сумма
  метаданные : "QR/NFC"
  подпись_клиента
  timestamp_создания
  статус : "несинхронизировано/подтверждено"
}

Client "1" -- "0..*" DigitalWallet : привязка
DigitalWallet "1" -- "0..*" OfflineOperation : содержит

class ClientAccount {
  идентификатор_счета
  остаток_средств
  валюта_счета
  флаг_цифрового_рубля : "да/нет"
}

Client "1" -- "0..*" ClientAccount : привязка

class PaymentOrder {
  идентификатор_поручения
  тип_операции : "оплата, перевод, пополнение"
  сумма
  дата_и_время_создания
  статус_исполнения
  код_цели_платежа
  референс_ЦБ
}

PaymentOrder "1" -- "1..2" ClientAccount : счет_списания/зачисления

class Transaction {
  идентификатор_транзакции
  дата_и_время
  сумма
  статус
  хэш_блокчейна_ЦБ
  подпись_банка
}

Transaction --> PaymentOrder : связь с поручением
Transaction --> OfflineOperation : подтверждает

class CBRIntegration {
  идентификатор_запроса
  тип_операции : "верификация/транзакция"
  статус_ответа
  timestamp_запроса
  timestamp_ответа
}

Transaction "1" -- "1" CBRIntegration : синхронизация
OfflineOperation "1" -- "0..1" CBRIntegration : подтверждение

class ProductService {
  идентификатор
  наименование
  категория
  стоимость
  код_ТН_ВЭД
}

class Message {
  идентификатор_сообщения
  тип_сообщения : "уведомление/запрос_ПОДФТ"
  дата_и_время_отправки
  содержание
  флаг_архивации : "да/нет"
}

Message "1" --> "1" Client : отправитель
Message "1" --> "1" Client : получатель
@enduml